export const AppImages = {
  logoTransparent: require("../../../public/images/logoTransparent.webp"),
  backgroundImage: require("../../../public/images/backgroundImage.webp"),
  sustIcon: require("../../../public/images/sustIcon.webp"),
  crainImage: require("../../../public/images/crainImage.webp"),
  videoThumbnail: require("../../../public/images/videoThumbnail.webp"),
  signature: require("../../../public/images/signature.webp"),
  gold: require("../../../public/images/gold.webp"),
  copper: require("../../../public/images/copper.webp"),
  background2: require("../../../public/images/background2.webp"),
  analysisIcon: require("../../../public/images/analysisIcon.webp"),
  blogImage: require("../../../public/images/blogImage.webp"),
  commentIcon: require("../../../public/images/commentIcon.webp"),
  diamonds: require("../../../public/images/diamonds.webp"),
  goldBg: require("../../../public/images/goldBg.webp"),
  footerBg: require("../../../public/images/footerBg.webp"),
  twitter: require("../../../public/images/twitter.webp"),
  facebook: require("../../../public/images/facebook.webp"),
  youtube: require("../../../public/images/youtube.webp"),
  instagram: require("../../../public/images/instagram.webp"),
  productsBg: require("../../../public/images/productsBg.webp"),
  phosphate2: require("../../../public/images/phosphate2.webp"),
  phosphate1: require("../../../public/images/phosphate1.webp"),
  dropdown: require("../../../public/images/dropdown.webp"),
  services1: require("../../../public/images/services1.webp"),
  services2: require("../../../public/images/services2.webp"),
};
